name: crypto_analyst
description: "Pet project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  talker: ^4.2.4
  talker_flutter: ^4.2.4
  talker_dio_logger: ^4.2.4
  talker_bloc_logger: ^4.2.4
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  get_it: ^7.7.0
  auto_route: ^8.2.0
  firebase_core: ^3.1.0
  equatable: ^2.0.5
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  isar_generator: *isar_version
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^8.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon_app.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/
